// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using ImagingClient.Infrastructure.Prism.Mvvm;
using Microsoft.Pex.Framework.Generated;

namespace VistA.Imaging.DataNavigator.ViewModels
{
    public partial class DataNavigationViewModelTest
    {
[TestMethod]
[PexGeneratedBy(typeof(DataNavigationViewModelTest))]
public void Constructor943()
{
    DataNavigationViewModel dataNavigationViewModel;
    dataNavigationViewModel = this.Constructor();
    Assert.IsNotNull((object)dataNavigationViewModel);
    Assert.IsNotNull(dataNavigationViewModel.SearchCommand);
    Assert.AreEqual<bool>(false, dataNavigationViewModel.SearchCommand.IsActive);
    Assert.IsNotNull(dataNavigationViewModel.CheckFileCommand);
    Assert.AreEqual<bool>(false, dataNavigationViewModel.CheckFileCommand.IsActive);
    Assert.IsNotNull(dataNavigationViewModel.SearchFiles);
    Assert.AreEqual<string>((string)null, dataNavigationViewModel.SearchFileText);
    Assert.IsNotNull(dataNavigationViewModel.EntryViewModels);
    Assert.IsNull(dataNavigationViewModel.SelectedSearchFile);
    Assert.IsNull(dataNavigationViewModel.SelectedSearchField);
    Assert.AreEqual<string>((string)null, dataNavigationViewModel.SearchText);
    Assert.AreEqual<bool>(false, ((ViewModel)dataNavigationViewModel).IsActive);
    Assert.IsNull(((ViewModel)dataNavigationViewModel).UIDispatcher);
}
    }
}
