// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using VistA.Imaging.DataNavigator.Model;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;
using ImagingClient.Infrastructure.Prism.Mvvm;

namespace VistA.Imaging.DataNavigator.ViewModels
{
    public partial class FilemanFileViewModelTest
    {
[TestMethod]
[PexGeneratedBy(typeof(FilemanFileViewModelTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ConstructorThrowsContractException592()
{
    try
    {
      FilemanFileViewModel filemanFileViewModel;
      filemanFileViewModel = this.Constructor((FilemanFile)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanFileViewModelTest))]
public void Constructor888()
{
    FilemanFileViewModel filemanFileViewModel;
    FilemanFile s0 = new FilemanFile();
    s0.Name = (string)null;
    s0.Number = (string)null;
    s0.Fields = (FilemanField[])null;
    filemanFileViewModel = this.Constructor(s0);
    Assert.IsNotNull((object)filemanFileViewModel);
    Assert.IsNotNull(filemanFileViewModel.File);
    Assert.AreEqual<string>((string)null, filemanFileViewModel.File.Name);
    Assert.AreEqual<string>((string)null, filemanFileViewModel.File.Number);
    Assert.IsNull(filemanFileViewModel.File.Fields);
    Assert.AreEqual<bool>(false, filemanFileViewModel.IsSelected);
    Assert.AreEqual<bool>(false, ((ViewModel)filemanFileViewModel).IsActive);
    Assert.IsNull(((ViewModel)filemanFileViewModel).UIDispatcher);
}
    }
}
