// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using ImagingClient.Infrastructure.Prism.Mvvm;
using Microsoft.Pex.Framework.Generated;

namespace VistA.Imaging.DataNavigator.ViewModels
{
    public partial class TreeNodeViewModelTest
    {
[TestMethod]
[PexGeneratedBy(typeof(TreeNodeViewModelTest))]
public void Constructor558()
{
    TreeNodeViewModel treeNodeViewModel;
    treeNodeViewModel = this.Constructor();
    Assert.IsNotNull((object)treeNodeViewModel);
    Assert.AreEqual<bool>(false, treeNodeViewModel.IsSelected);
    Assert.AreEqual<bool>(false, treeNodeViewModel.IsExpanded);
    Assert.AreEqual<bool>(false, treeNodeViewModel.AreChildrenLoaded);
    Assert.IsNull(treeNodeViewModel.Parent);
    Assert.IsNotNull(treeNodeViewModel.Children);
    Assert.AreEqual<bool>(false, ((ViewModel)treeNodeViewModel).IsActive);
    Assert.IsNull(((ViewModel)treeNodeViewModel).UIDispatcher);
}
    }
}
