// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace VistA.Imaging.Collections
{
    public partial class ReadOnlyDictionaryTKeyTValueTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ReadOnlyDictionaryTKeyTValueTest))]
public void ContainsKey464()
{
    ReadOnlyDictionary<int, int> readOnlyDictionary;
    bool b;
    readOnlyDictionary = new ReadOnlyDictionary<int, int>();
    b = this.ContainsKey<int, int>(readOnlyDictionary, 0);
    Assert.AreEqual<bool>(false, b);
    Assert.IsNotNull((object)readOnlyDictionary);
}
    }
}
