// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace VistA.Imaging.Collections
{
    public partial class ReadOnlyDictionaryTKeyTValueTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ReadOnlyDictionaryTKeyTValueTest))]
public void CopyTo857()
{
    ReadOnlyDictionary<int, int> readOnlyDictionary;
    readOnlyDictionary = new ReadOnlyDictionary<int, int>();
    KeyValuePair<int, int>[] keyValuePairs = new KeyValuePair<int, int>[0];
    this.CopyTo<int, int>(readOnlyDictionary, keyValuePairs, 0);
    Assert.IsNotNull((object)readOnlyDictionary);
}
[TestMethod]
[PexGeneratedBy(typeof(ReadOnlyDictionaryTKeyTValueTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void CopyToThrowsContractException427()
{
    try
    {
      ReadOnlyDictionary<int, int> readOnlyDictionary;
      readOnlyDictionary = new ReadOnlyDictionary<int, int>();
      this.CopyTo<int, int>(readOnlyDictionary, (KeyValuePair<int, int>[])null, 0);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
