// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework.Generated;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace VistA.Imaging.Collections
{
    public partial class ReadOnlyDictionaryTKeyTValueTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ReadOnlyDictionaryTKeyTValueTest))]
public void GetEnumerator650()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      ReadOnlyDictionary<int, int> readOnlyDictionary;
      IEnumerator<KeyValuePair<int, int>> iEnumerator;
      readOnlyDictionary = new ReadOnlyDictionary<int, int>();
      iEnumerator = this.GetEnumerator<int, int>(readOnlyDictionary);
      disposables.Add((IDisposable)iEnumerator);
      disposables.Dispose();
      Assert.IsNotNull((object)readOnlyDictionary);
    }
}
    }
}
