// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace VistA.Imaging.Viewer.AWIV
{
    public partial class AwivParameterDictionaryTest
    {
[TestMethod]
[PexGeneratedBy(typeof(AwivParameterDictionaryTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException792()
{
    AwivParameterDictionary awivParameterDictionary;
    awivParameterDictionary = this.Constructor((string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(AwivParameterDictionaryTest))]
public void Constructor747()
{
    AwivParameterDictionary awivParameterDictionary;
    awivParameterDictionary = this.Constructor("");
    Assert.IsNotNull((object)awivParameterDictionary);
}
[TestMethod]
[PexGeneratedBy(typeof(AwivParameterDictionaryTest))]
public void Constructor411()
{
    AwivParameterDictionary awivParameterDictionary;
    awivParameterDictionary = this.Constructor("&");
    Assert.IsNotNull((object)awivParameterDictionary);
}
[TestMethod]
[PexGeneratedBy(typeof(AwivParameterDictionaryTest))]
public void Constructor856()
{
    AwivParameterDictionary awivParameterDictionary;
    awivParameterDictionary = this.Constructor("&\0");
    Assert.IsNotNull((object)awivParameterDictionary);
}
[TestMethod]
[PexGeneratedBy(typeof(AwivParameterDictionaryTest))]
public void Constructor245()
{
    AwivParameterDictionary awivParameterDictionary;
    awivParameterDictionary = this.Constructor("&A");
    Assert.IsNotNull((object)awivParameterDictionary);
}
[TestMethod]
[PexGeneratedBy(typeof(AwivParameterDictionaryTest))]
public void Constructor615()
{
    AwivParameterDictionary awivParameterDictionary;
    awivParameterDictionary = this.Constructor("&A{\0");
    Assert.IsNotNull((object)awivParameterDictionary);
}
[TestMethod]
[PexGeneratedBy(typeof(AwivParameterDictionaryTest))]
public void Constructor610()
{
    AwivParameterDictionary awivParameterDictionary;
    awivParameterDictionary = this.Constructor("&A{}");
    Assert.IsNotNull((object)awivParameterDictionary);
}
[TestMethod]
[PexGeneratedBy(typeof(AwivParameterDictionaryTest))]
[ExpectedException(typeof(AwivParameterException))]
public void ConstructorThrowsAwivParameterException877()
{
    AwivParameterDictionary awivParameterDictionary;
    awivParameterDictionary = this.Constructor("&A{}&A{}");
}
[TestMethod]
[PexGeneratedBy(typeof(AwivParameterDictionaryTest))]
public void Constructor37()
{
    AwivParameterDictionary awivParameterDictionary;
    awivParameterDictionary = this.Constructor("&G{}&P{}");
    Assert.IsNotNull((object)awivParameterDictionary);
}
[TestMethod]
[PexGeneratedBy(typeof(AwivParameterDictionaryTest))]
[ExpectedException(typeof(AwivParameterException))]
public void ConstructorThrowsAwivParameterException252()
{
    AwivParameterDictionary awivParameterDictionary;
    awivParameterDictionary = this.Constructor("&P{}&G{}&G{}");
}
[TestMethod]
[PexGeneratedBy(typeof(AwivParameterDictionaryTest))]
[ExpectedException(typeof(AwivParameterException))]
public void ConstructorThrowsAwivParameterException648()
{
    AwivParameterDictionary awivParameterDictionary;
    awivParameterDictionary = this.Constructor("&I{}&C{}&C{\0\0}");
}
    }
}
