// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace VistA.Imaging.Viewer.AWIV
{
    public partial class AwivParameterDictionaryTest
    {
[TestMethod]
[PexGeneratedBy(typeof(AwivParameterDictionaryTest))]
[ExpectedException(typeof(AwivParameterException))]
public void SiteServiceUrlGetThrowsAwivParameterException119()
{
    AwivParameterDictionary awivParameterDictionary;
    Uri uri;
    awivParameterDictionary = new AwivParameterDictionary("");
    uri = this.SiteServiceUrlGet(awivParameterDictionary);
}
[TestMethod]
[PexGeneratedBy(typeof(AwivParameterDictionaryTest))]
[ExpectedException(typeof(AwivParameterException))]
public void SiteServiceUrlGetThrowsAwivParameterException973()
{
    AwivParameterDictionary awivParameterDictionary;
    Uri uri;
    awivParameterDictionary = new AwivParameterDictionary("&");
    uri = this.SiteServiceUrlGet(awivParameterDictionary);
}
[TestMethod]
[PexGeneratedBy(typeof(AwivParameterDictionaryTest))]
[ExpectedException(typeof(AwivParameterException))]
public void SiteServiceUrlGetThrowsAwivParameterException538()
{
    AwivParameterDictionary awivParameterDictionary;
    Uri uri;
    awivParameterDictionary = new AwivParameterDictionary("&\0");
    uri = this.SiteServiceUrlGet(awivParameterDictionary);
}
[TestMethod]
[PexGeneratedBy(typeof(AwivParameterDictionaryTest))]
[ExpectedException(typeof(AwivParameterException))]
public void SiteServiceUrlGetThrowsAwivParameterException875()
{
    AwivParameterDictionary awivParameterDictionary;
    Uri uri;
    awivParameterDictionary = new AwivParameterDictionary("&A");
    uri = this.SiteServiceUrlGet(awivParameterDictionary);
}
[TestMethod]
[PexGeneratedBy(typeof(AwivParameterDictionaryTest))]
[ExpectedException(typeof(AwivParameterException))]
public void SiteServiceUrlGetThrowsAwivParameterException936()
{
    AwivParameterDictionary awivParameterDictionary;
    Uri uri;
    awivParameterDictionary = new AwivParameterDictionary("&A{\0");
    uri = this.SiteServiceUrlGet(awivParameterDictionary);
}
[TestMethod]
[PexGeneratedBy(typeof(AwivParameterDictionaryTest))]
[ExpectedException(typeof(AwivParameterException))]
public void SiteServiceUrlGetThrowsAwivParameterException934()
{
    AwivParameterDictionary awivParameterDictionary;
    Uri uri;
    awivParameterDictionary = new AwivParameterDictionary("&A{}");
    uri = this.SiteServiceUrlGet(awivParameterDictionary);
}
[TestMethod]
[PexGeneratedBy(typeof(AwivParameterDictionaryTest))]
[ExpectedException(typeof(AwivParameterException))]
public void SiteServiceUrlGetThrowsAwivParameterException876()
{
    AwivParameterDictionary awivParameterDictionary;
    Uri uri;
    awivParameterDictionary = new AwivParameterDictionary("&J{}&P{}");
    uri = this.SiteServiceUrlGet(awivParameterDictionary);
}
    }
}
