// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using System.Collections.Generic;

namespace VistA.Imaging.Viewer.AWIV
{
    public partial class AwivParameterDictionaryTest
    {
[TestMethod]
[PexGeneratedBy(typeof(AwivParameterDictionaryTest))]
[ExpectedException(typeof(AwivParameterException))]
public void CVIXSiteNumberGetThrowsAwivParameterException362()
{
    AwivParameterDictionary awivParameterDictionary;
    string s;
    awivParameterDictionary = new AwivParameterDictionary("");
    s = this.CVIXSiteNumberGet(awivParameterDictionary);
}
[TestMethod]
[PexGeneratedBy(typeof(AwivParameterDictionaryTest))]
[ExpectedException(typeof(AwivParameterException))]
public void CVIXSiteNumberGetThrowsAwivParameterException769()
{
    AwivParameterDictionary awivParameterDictionary;
    string s;
    awivParameterDictionary = new AwivParameterDictionary("&");
    s = this.CVIXSiteNumberGet(awivParameterDictionary);
}
[TestMethod]
[PexGeneratedBy(typeof(AwivParameterDictionaryTest))]
[ExpectedException(typeof(AwivParameterException))]
public void CVIXSiteNumberGetThrowsAwivParameterException739()
{
    AwivParameterDictionary awivParameterDictionary;
    string s;
    awivParameterDictionary = new AwivParameterDictionary("&\0");
    s = this.CVIXSiteNumberGet(awivParameterDictionary);
}
[TestMethod]
[PexGeneratedBy(typeof(AwivParameterDictionaryTest))]
[ExpectedException(typeof(AwivParameterException))]
public void CVIXSiteNumberGetThrowsAwivParameterException285()
{
    AwivParameterDictionary awivParameterDictionary;
    string s;
    awivParameterDictionary = new AwivParameterDictionary("&A");
    s = this.CVIXSiteNumberGet(awivParameterDictionary);
}
[TestMethod]
[PexGeneratedBy(typeof(AwivParameterDictionaryTest))]
[ExpectedException(typeof(AwivParameterException))]
public void CVIXSiteNumberGetThrowsAwivParameterException399()
{
    AwivParameterDictionary awivParameterDictionary;
    string s;
    awivParameterDictionary = new AwivParameterDictionary("&A{\0");
    s = this.CVIXSiteNumberGet(awivParameterDictionary);
}
[TestMethod]
[PexGeneratedBy(typeof(AwivParameterDictionaryTest))]
[ExpectedException(typeof(AwivParameterException))]
public void CVIXSiteNumberGetThrowsAwivParameterException602()
{
    AwivParameterDictionary awivParameterDictionary;
    string s;
    awivParameterDictionary = new AwivParameterDictionary("&A{}");
    s = this.CVIXSiteNumberGet(awivParameterDictionary);
}
    }
}
