// <copyright file="HierarchicalEntryLoadViewModelFactoryTest.CreateHierarchicalEntryLoadViewModel.g.cs" company="Department of Veterans Affairs">Copyright © Department of Veterans Affairs 2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using VistA.Imaging.DataNavigator.Repositories.Moles;
using VistA.Imaging.DataNavigator.ViewModels.Factories.Moles;
using VistA.Imaging.DataNavigator.ViewModels;
using VistA.Imaging.DataNavigator.Repositories;
using VistA.Imaging.DataNavigator.Model;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using VistA.Imaging.DataNavigator.Model.Moles;
using Microsoft.Pex.Framework.Moles;
using VistA.Imaging.DataNavigator.ViewModels.Moles;
using ImagingClient.Infrastructure.Prism.Mvvm;

namespace VistA.Imaging.DataNavigator.ViewModels.Factories
{
    public partial class HierarchicalEntryLoadViewModelFactoryTest
    {
[TestMethod]
[PexGeneratedBy(typeof(HierarchicalEntryLoadViewModelFactoryTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void CreateHierarchicalEntryLoadViewModelThrowsArgumentNullException517()
{
    SIFilemanEntryRepository sIFilemanEntryRepository;
    SIHierarchicalEntryViewModelFactory sIHierarchicalEntryViewModelFactory;
    HierarchicalEntryLoadViewModelFactory hierarchicalEntryLoadViewModelFactory;
    HierarchicalEntryLoadViewModel hierarchicalEntryLoadViewModel;
    sIFilemanEntryRepository = new SIFilemanEntryRepository();
    sIHierarchicalEntryViewModelFactory = new SIHierarchicalEntryViewModelFactory();
    hierarchicalEntryLoadViewModelFactory =
      HierarchicalEntryLoadViewModelFactoryFactory.Create
          ((IFilemanEntryRepository)sIFilemanEntryRepository, 
           (IHierarchicalEntryViewModelFactory)sIHierarchicalEntryViewModelFactory);
    hierarchicalEntryLoadViewModel = this.CreateHierarchicalEntryLoadViewModel
                                         (hierarchicalEntryLoadViewModelFactory, 
                                          (FilemanFilePointer)null, (TreeNodeViewModel)null);
}
[TestMethod]
[PexGeneratedBy(typeof(HierarchicalEntryLoadViewModelFactoryTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void CreateHierarchicalEntryLoadViewModelThrowsArgumentNullException303()
{
    SIFilemanEntryRepository sIFilemanEntryRepository;
    SIHierarchicalEntryViewModelFactory sIHierarchicalEntryViewModelFactory;
    HierarchicalEntryLoadViewModelFactory hierarchicalEntryLoadViewModelFactory;
    SIFilemanFileRepository sIFilemanFileRepository;
    SFilemanFilePointer sFilemanFilePointer;
    HierarchicalEntryLoadViewModel hierarchicalEntryLoadViewModel;
    sIFilemanEntryRepository = new SIFilemanEntryRepository();
    sIHierarchicalEntryViewModelFactory = new SIHierarchicalEntryViewModelFactory();
    hierarchicalEntryLoadViewModelFactory =
      HierarchicalEntryLoadViewModelFactoryFactory.Create
          ((IFilemanEntryRepository)sIFilemanEntryRepository, 
           (IHierarchicalEntryViewModelFactory)sIHierarchicalEntryViewModelFactory);
    sIFilemanFileRepository = new SIFilemanFileRepository();
    FilemanField s0 = new FilemanField();
    s0.DataType = (string)null;
    s0.File = (FilemanFile)null;
    s0.IsIndexed = false;
    s0.Name = (string)null;
    s0.Number = (string)null;
    s0.Pointer = (FilemanFilePointer)null;
    s0.PointerFileNumber = (string)null;
    sFilemanFilePointer = new SFilemanFilePointer
                              ((IFilemanFileRepository)sIFilemanFileRepository, s0, "\0");
    hierarchicalEntryLoadViewModel = this.CreateHierarchicalEntryLoadViewModel
                                         (hierarchicalEntryLoadViewModelFactory, 
                                          (FilemanFilePointer)sFilemanFilePointer, (TreeNodeViewModel)null);
}
[TestMethod]
[PexGeneratedBy(typeof(HierarchicalEntryLoadViewModelFactoryTest))]
public void CreateHierarchicalEntryLoadViewModel756()
{
    using (PexChooseBehavedBehavior.Setup())
    {
      SIFilemanEntryRepository sIFilemanEntryRepository;
      SIHierarchicalEntryViewModelFactory sIHierarchicalEntryViewModelFactory;
      HierarchicalEntryLoadViewModelFactory hierarchicalEntryLoadViewModelFactory;
      SIFilemanFileRepository sIFilemanFileRepository;
      SFilemanFilePointer sFilemanFilePointer;
      STreeNodeViewModel sTreeNodeViewModel;
      HierarchicalEntryLoadViewModel hierarchicalEntryLoadViewModel;
      sIFilemanEntryRepository = new SIFilemanEntryRepository();
      sIHierarchicalEntryViewModelFactory =
        new SIHierarchicalEntryViewModelFactory();
      hierarchicalEntryLoadViewModelFactory =
        HierarchicalEntryLoadViewModelFactoryFactory.Create
            ((IFilemanEntryRepository)sIFilemanEntryRepository, 
             (IHierarchicalEntryViewModelFactory)sIHierarchicalEntryViewModelFactory);
      sIFilemanFileRepository = new SIFilemanFileRepository();
      FilemanField s0 = new FilemanField();
      s0.DataType = (string)null;
      s0.File = (FilemanFile)null;
      s0.IsIndexed = false;
      s0.Name = (string)null;
      s0.Number = (string)null;
      s0.Pointer = (FilemanFilePointer)null;
      s0.PointerFileNumber = (string)null;
      sFilemanFilePointer = new SFilemanFilePointer
                                ((IFilemanFileRepository)sIFilemanFileRepository, s0, "\u0100");
      sTreeNodeViewModel = new STreeNodeViewModel();
      hierarchicalEntryLoadViewModel = this.CreateHierarchicalEntryLoadViewModel
                                           (hierarchicalEntryLoadViewModelFactory, 
                                            (FilemanFilePointer)sFilemanFilePointer, 
                                            (TreeNodeViewModel)sTreeNodeViewModel);
      Assert.IsNotNull((object)hierarchicalEntryLoadViewModel);
      Assert.IsNotNull(hierarchicalEntryLoadViewModel.Pointer);
      Assert.IsNotNull(hierarchicalEntryLoadViewModel.Pointer.SourceField);
      Assert.AreEqual<string>
          ((string)null, hierarchicalEntryLoadViewModel.Pointer.SourceField.DataType);
      Assert.IsNull(hierarchicalEntryLoadViewModel.Pointer.SourceField.File);
      Assert.AreEqual<bool>
          (false, hierarchicalEntryLoadViewModel.Pointer.SourceField.IsIndexed);
      Assert.AreEqual<string>
          ((string)null, hierarchicalEntryLoadViewModel.Pointer.SourceField.Name);
      Assert.AreEqual<string>
          ((string)null, hierarchicalEntryLoadViewModel.Pointer.SourceField.Number);
      Assert.IsNull(hierarchicalEntryLoadViewModel.Pointer.SourceField.Pointer);
      Assert.AreEqual<string>((string)null, 
                              hierarchicalEntryLoadViewModel.Pointer.SourceField.PointerFileNumber);
      Assert.AreEqual<bool>(false, hierarchicalEntryLoadViewModel.IsSelected);
      Assert.AreEqual<bool>
          (false, ((TreeNodeViewModel)hierarchicalEntryLoadViewModel).IsSelected);
      Assert.AreEqual<bool>
          (false, ((TreeNodeViewModel)hierarchicalEntryLoadViewModel).IsExpanded);
      Assert.AreEqual<bool>(false, 
                            ((TreeNodeViewModel)hierarchicalEntryLoadViewModel).AreChildrenLoaded);
      Assert.IsNotNull(((TreeNodeViewModel)hierarchicalEntryLoadViewModel).Parent);
      Assert.AreEqual<bool>(false, 
                            ((TreeNodeViewModel)hierarchicalEntryLoadViewModel).Parent.IsSelected);
      Assert.AreEqual<bool>(false, 
                            ((TreeNodeViewModel)hierarchicalEntryLoadViewModel).Parent.IsExpanded);
      Assert.AreEqual<bool>
          (false, ((TreeNodeViewModel)hierarchicalEntryLoadViewModel).Parent
                    .AreChildrenLoaded);
      Assert.IsNull
          (((TreeNodeViewModel)hierarchicalEntryLoadViewModel).Parent.Parent);
      Assert.IsNotNull
          (((TreeNodeViewModel)hierarchicalEntryLoadViewModel).Parent.Children);
      Assert.AreEqual<bool>(false, 
                            ((TreeNodeViewModel)hierarchicalEntryLoadViewModel).Parent.IsActive);
      Assert.IsNull
          (((TreeNodeViewModel)hierarchicalEntryLoadViewModel).Parent.UIDispatcher);
      Assert.IsNotNull(((TreeNodeViewModel)hierarchicalEntryLoadViewModel).Children);
      Assert.AreEqual<bool>
          (false, ((ViewModel)hierarchicalEntryLoadViewModel).IsActive);
      Assert.IsNull(((ViewModel)hierarchicalEntryLoadViewModel).UIDispatcher);
      Assert.IsNotNull((object)hierarchicalEntryLoadViewModelFactory);
      Assert.IsNotNull
          (hierarchicalEntryLoadViewModelFactory.HierarchicalEntryViewModelFactory);
    }
}
    }
}
