//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImagingExchangeRegionTO", Namespace="http://vistaweb.med.va.gov/webservices/ImagingExchangeSiteService")]
    [System.SerializableAttribute()]
    public partial class ImagingExchangeRegionTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.ImagingExchangeSiteTO[] sitesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.FaultTO faultTOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.ImagingExchangeSiteTO[] sites {
            get {
                return this.sitesField;
            }
            set {
                if ((object.ReferenceEquals(this.sitesField, value) != true)) {
                    this.sitesField = value;
                    this.RaisePropertyChanged("sites");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.FaultTO faultTO {
            get {
                return this.faultTOField;
            }
            set {
                if ((object.ReferenceEquals(this.faultTOField, value) != true)) {
                    this.faultTOField = value;
                    this.RaisePropertyChanged("faultTO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultTO", Namespace="http://vistaweb.med.va.gov/webservices/ImagingExchangeSiteService")]
    [System.SerializableAttribute()]
    public partial class FaultTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string suggestionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string stackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.stackTraceField, value) != true)) {
                    this.stackTraceField = value;
                    this.RaisePropertyChanged("stackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string suggestion {
            get {
                return this.suggestionField;
            }
            set {
                if ((object.ReferenceEquals(this.suggestionField, value) != true)) {
                    this.suggestionField = value;
                    this.RaisePropertyChanged("suggestion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImagingExchangeSiteTO", Namespace="http://vistaweb.med.va.gov/webservices/ImagingExchangeSiteService")]
    [System.SerializableAttribute()]
    public partial class ImagingExchangeSiteTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string siteNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string siteNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string regionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string siteAbbrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vistaServerField;
        
        private int vistaPortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string acceleratorServerField;
        
        private int acceleratorPortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.FaultTO faultTOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string siteNumber {
            get {
                return this.siteNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.siteNumberField, value) != true)) {
                    this.siteNumberField = value;
                    this.RaisePropertyChanged("siteNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string siteName {
            get {
                return this.siteNameField;
            }
            set {
                if ((object.ReferenceEquals(this.siteNameField, value) != true)) {
                    this.siteNameField = value;
                    this.RaisePropertyChanged("siteName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string regionID {
            get {
                return this.regionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.regionIDField, value) != true)) {
                    this.regionIDField = value;
                    this.RaisePropertyChanged("regionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string siteAbbr {
            get {
                return this.siteAbbrField;
            }
            set {
                if ((object.ReferenceEquals(this.siteAbbrField, value) != true)) {
                    this.siteAbbrField = value;
                    this.RaisePropertyChanged("siteAbbr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string vistaServer {
            get {
                return this.vistaServerField;
            }
            set {
                if ((object.ReferenceEquals(this.vistaServerField, value) != true)) {
                    this.vistaServerField = value;
                    this.RaisePropertyChanged("vistaServer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int vistaPort {
            get {
                return this.vistaPortField;
            }
            set {
                if ((this.vistaPortField.Equals(value) != true)) {
                    this.vistaPortField = value;
                    this.RaisePropertyChanged("vistaPort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string acceleratorServer {
            get {
                return this.acceleratorServerField;
            }
            set {
                if ((object.ReferenceEquals(this.acceleratorServerField, value) != true)) {
                    this.acceleratorServerField = value;
                    this.RaisePropertyChanged("acceleratorServer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int acceleratorPort {
            get {
                return this.acceleratorPortField;
            }
            set {
                if ((this.acceleratorPortField.Equals(value) != true)) {
                    this.acceleratorPortField = value;
                    this.RaisePropertyChanged("acceleratorPort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.FaultTO faultTO {
            get {
                return this.faultTOField;
            }
            set {
                if ((object.ReferenceEquals(this.faultTOField, value) != true)) {
                    this.faultTOField = value;
                    this.RaisePropertyChanged("faultTO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://vistaweb.med.va.gov/webservices/ImagingExchangeSiteService", ConfigurationName="ImagingExchangeSiteService.ImagingExchangeSiteServiceSoap")]
    public interface ImagingExchangeSiteServiceSoap {
        
        // CODEGEN: Generating message contract since element name regionID from namespace http://vistaweb.med.va.gov/webservices/ImagingExchangeSiteService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://vistaweb.med.va.gov/webservices/ImagingExchangeSiteService/getVISN", ReplyAction="*")]
        VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getVISNResponse getVISN(VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getVISNRequest request);
        
        // CODEGEN: Generating message contract since element name siteIDs from namespace http://vistaweb.med.va.gov/webservices/ImagingExchangeSiteService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://vistaweb.med.va.gov/webservices/ImagingExchangeSiteService/getSites", ReplyAction="*")]
        VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getSitesResponse getSites(VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getSitesRequest request);
        
        // CODEGEN: Generating message contract since element name siteID from namespace http://vistaweb.med.va.gov/webservices/ImagingExchangeSiteService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://vistaweb.med.va.gov/webservices/ImagingExchangeSiteService/getSite", ReplyAction="*")]
        VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getSiteResponse getSite(VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getSiteRequest request);
        
        // CODEGEN: Generating message contract since element name getImagingExchangeSitesResult from namespace http://vistaweb.med.va.gov/webservices/ImagingExchangeSiteService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://vistaweb.med.va.gov/webservices/ImagingExchangeSiteService/getImagingExcha" +
            "ngeSites", ReplyAction="*")]
        VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getImagingExchangeSitesResponse getImagingExchangeSites(VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getImagingExchangeSitesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVISNRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVISN", Namespace="http://vistaweb.med.va.gov/webservices/ImagingExchangeSiteService", Order=0)]
        public VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getVISNRequestBody Body;
        
        public getVISNRequest() {
        }
        
        public getVISNRequest(VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getVISNRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vistaweb.med.va.gov/webservices/ImagingExchangeSiteService")]
    public partial class getVISNRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string regionID;
        
        public getVISNRequestBody() {
        }
        
        public getVISNRequestBody(string regionID) {
            this.regionID = regionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVISNResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVISNResponse", Namespace="http://vistaweb.med.va.gov/webservices/ImagingExchangeSiteService", Order=0)]
        public VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getVISNResponseBody Body;
        
        public getVISNResponse() {
        }
        
        public getVISNResponse(VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getVISNResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vistaweb.med.va.gov/webservices/ImagingExchangeSiteService")]
    public partial class getVISNResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.ImagingExchangeRegionTO getVISNResult;
        
        public getVISNResponseBody() {
        }
        
        public getVISNResponseBody(VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.ImagingExchangeRegionTO getVISNResult) {
            this.getVISNResult = getVISNResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSitesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSites", Namespace="http://vistaweb.med.va.gov/webservices/ImagingExchangeSiteService", Order=0)]
        public VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getSitesRequestBody Body;
        
        public getSitesRequest() {
        }
        
        public getSitesRequest(VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getSitesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vistaweb.med.va.gov/webservices/ImagingExchangeSiteService")]
    public partial class getSitesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string siteIDs;
        
        public getSitesRequestBody() {
        }
        
        public getSitesRequestBody(string siteIDs) {
            this.siteIDs = siteIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSitesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSitesResponse", Namespace="http://vistaweb.med.va.gov/webservices/ImagingExchangeSiteService", Order=0)]
        public VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getSitesResponseBody Body;
        
        public getSitesResponse() {
        }
        
        public getSitesResponse(VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getSitesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vistaweb.med.va.gov/webservices/ImagingExchangeSiteService")]
    public partial class getSitesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.ImagingExchangeSiteTO[] getSitesResult;
        
        public getSitesResponseBody() {
        }
        
        public getSitesResponseBody(VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.ImagingExchangeSiteTO[] getSitesResult) {
            this.getSitesResult = getSitesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSiteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSite", Namespace="http://vistaweb.med.va.gov/webservices/ImagingExchangeSiteService", Order=0)]
        public VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getSiteRequestBody Body;
        
        public getSiteRequest() {
        }
        
        public getSiteRequest(VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getSiteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vistaweb.med.va.gov/webservices/ImagingExchangeSiteService")]
    public partial class getSiteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string siteID;
        
        public getSiteRequestBody() {
        }
        
        public getSiteRequestBody(string siteID) {
            this.siteID = siteID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSiteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSiteResponse", Namespace="http://vistaweb.med.va.gov/webservices/ImagingExchangeSiteService", Order=0)]
        public VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getSiteResponseBody Body;
        
        public getSiteResponse() {
        }
        
        public getSiteResponse(VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getSiteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vistaweb.med.va.gov/webservices/ImagingExchangeSiteService")]
    public partial class getSiteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.ImagingExchangeSiteTO getSiteResult;
        
        public getSiteResponseBody() {
        }
        
        public getSiteResponseBody(VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.ImagingExchangeSiteTO getSiteResult) {
            this.getSiteResult = getSiteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getImagingExchangeSitesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getImagingExchangeSites", Namespace="http://vistaweb.med.va.gov/webservices/ImagingExchangeSiteService", Order=0)]
        public VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getImagingExchangeSitesRequestBody Body;
        
        public getImagingExchangeSitesRequest() {
        }
        
        public getImagingExchangeSitesRequest(VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getImagingExchangeSitesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getImagingExchangeSitesRequestBody {
        
        public getImagingExchangeSitesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getImagingExchangeSitesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getImagingExchangeSitesResponse", Namespace="http://vistaweb.med.va.gov/webservices/ImagingExchangeSiteService", Order=0)]
        public VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getImagingExchangeSitesResponseBody Body;
        
        public getImagingExchangeSitesResponse() {
        }
        
        public getImagingExchangeSitesResponse(VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getImagingExchangeSitesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vistaweb.med.va.gov/webservices/ImagingExchangeSiteService")]
    public partial class getImagingExchangeSitesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.ImagingExchangeSiteTO[] getImagingExchangeSitesResult;
        
        public getImagingExchangeSitesResponseBody() {
        }
        
        public getImagingExchangeSitesResponseBody(VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.ImagingExchangeSiteTO[] getImagingExchangeSitesResult) {
            this.getImagingExchangeSitesResult = getImagingExchangeSitesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImagingExchangeSiteServiceSoapChannel : VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.ImagingExchangeSiteServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImagingExchangeSiteServiceSoapClient : System.ServiceModel.ClientBase<VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.ImagingExchangeSiteServiceSoap>, VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.ImagingExchangeSiteServiceSoap {
        
        public ImagingExchangeSiteServiceSoapClient() {
        }
        
        public ImagingExchangeSiteServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImagingExchangeSiteServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImagingExchangeSiteServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImagingExchangeSiteServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getVISNResponse VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.ImagingExchangeSiteServiceSoap.getVISN(VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getVISNRequest request) {
            return base.Channel.getVISN(request);
        }
        
        public VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.ImagingExchangeRegionTO getVISN(string regionID) {
            VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getVISNRequest inValue = new VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getVISNRequest();
            inValue.Body = new VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getVISNRequestBody();
            inValue.Body.regionID = regionID;
            VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getVISNResponse retVal = ((VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.ImagingExchangeSiteServiceSoap)(this)).getVISN(inValue);
            return retVal.Body.getVISNResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getSitesResponse VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.ImagingExchangeSiteServiceSoap.getSites(VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getSitesRequest request) {
            return base.Channel.getSites(request);
        }
        
        public VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.ImagingExchangeSiteTO[] getSites(string siteIDs) {
            VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getSitesRequest inValue = new VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getSitesRequest();
            inValue.Body = new VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getSitesRequestBody();
            inValue.Body.siteIDs = siteIDs;
            VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getSitesResponse retVal = ((VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.ImagingExchangeSiteServiceSoap)(this)).getSites(inValue);
            return retVal.Body.getSitesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getSiteResponse VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.ImagingExchangeSiteServiceSoap.getSite(VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getSiteRequest request) {
            return base.Channel.getSite(request);
        }
        
        public VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.ImagingExchangeSiteTO getSite(string siteID) {
            VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getSiteRequest inValue = new VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getSiteRequest();
            inValue.Body = new VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getSiteRequestBody();
            inValue.Body.siteID = siteID;
            VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getSiteResponse retVal = ((VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.ImagingExchangeSiteServiceSoap)(this)).getSite(inValue);
            return retVal.Body.getSiteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getImagingExchangeSitesResponse VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.ImagingExchangeSiteServiceSoap.getImagingExchangeSites(VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getImagingExchangeSitesRequest request) {
            return base.Channel.getImagingExchangeSites(request);
        }
        
        public VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.ImagingExchangeSiteTO[] getImagingExchangeSites() {
            VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getImagingExchangeSitesRequest inValue = new VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getImagingExchangeSitesRequest();
            inValue.Body = new VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getImagingExchangeSitesRequestBody();
            VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.getImagingExchangeSitesResponse retVal = ((VistA.Imaging.Telepathology.Communication.ImagingExchangeSiteService.ImagingExchangeSiteServiceSoap)(this)).getImagingExchangeSites(inValue);
            return retVal.Body.getImagingExchangeSitesResult;
        }
    }
}
