// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace VistA.Imaging.DataNavigator.Model
{
    public partial class FilemanEntryTest
    {
[TestMethod]
[PexGeneratedBy(typeof(FilemanEntryTest))]
public void ItemGet915()
{
    FilemanFieldValue filemanFieldValue;
    FilemanEntry s0 = new FilemanEntry();
    s0.Ien = (string)null;
    s0.File = (FilemanFile)null;
    s0.Values = (FilemanFieldValue[])null;
    filemanFieldValue = this.ItemGet(s0, (string)null);
    Assert.IsNull((object)filemanFieldValue);
    Assert.IsNotNull((object)s0);
    Assert.AreEqual<string>((string)null, s0.Ien);
    Assert.IsNull(s0.File);
    Assert.IsNull(s0.Values);
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanEntryTest))]
public void ItemGet943()
{
    FilemanFieldValue filemanFieldValue;
    FilemanEntry s0 = new FilemanEntry();
    s0.Ien = (string)null;
    s0.File = (FilemanFile)null;
    FilemanFieldValue[] filemanFieldValues = new FilemanFieldValue[0];
    s0.Values = filemanFieldValues;
    filemanFieldValue = this.ItemGet(s0, (string)null);
    Assert.IsNull((object)filemanFieldValue);
    Assert.IsNotNull((object)s0);
    Assert.AreEqual<string>((string)null, s0.Ien);
    Assert.IsNull(s0.File);
    Assert.IsNotNull(s0.Values);
    Assert.AreEqual<int>(0, s0.Values.Length);
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanEntryTest))]
public void ItemGet869()
{
    FilemanFieldValue filemanFieldValue;
    FilemanEntry s0 = new FilemanEntry();
    s0.Ien = (string)null;
    s0.File = (FilemanFile)null;
    FilemanFieldValue[] filemanFieldValues = new FilemanFieldValue[1];
    s0.Values = filemanFieldValues;
    filemanFieldValue = this.ItemGet(s0, (string)null);
    Assert.IsNull((object)filemanFieldValue);
    Assert.IsNotNull((object)s0);
    Assert.AreEqual<string>((string)null, s0.Ien);
    Assert.IsNull(s0.File);
    Assert.IsNotNull(s0.Values);
    Assert.AreEqual<int>(1, s0.Values.Length);
    Assert.IsNull((object)(s0.Values[0]));
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanEntryTest))]
public void ItemGet403()
{
    FilemanFieldValue filemanFieldValue;
    FilemanEntry s0 = new FilemanEntry();
    s0.Ien = (string)null;
    s0.File = (FilemanFile)null;
    FilemanFieldValue[] filemanFieldValues = new FilemanFieldValue[1];
    s0.Values = filemanFieldValues;
    FilemanFieldValue s1 = new FilemanFieldValue();
    s1.Field = (FilemanField)null;
    s1.FieldNumber = (string)null;
    s1.InternalValue = (string)null;
    s1.ExternalValue = (string)null;
    filemanFieldValues[0] = s1;
    filemanFieldValue = this.ItemGet(s0, (string)null);
    Assert.IsNotNull((object)filemanFieldValue);
    Assert.IsNull(filemanFieldValue.Field);
    Assert.AreEqual<string>((string)null, filemanFieldValue.FieldNumber);
    Assert.AreEqual<string>((string)null, filemanFieldValue.InternalValue);
    Assert.AreEqual<string>((string)null, filemanFieldValue.ExternalValue);
    Assert.IsNotNull((object)s0);
    Assert.AreEqual<string>((string)null, s0.Ien);
    Assert.IsNull(s0.File);
    Assert.IsNotNull(s0.Values);
    Assert.AreEqual<int>(1, s0.Values.Length);
    Assert.IsNotNull((object)(s0.Values[0]));
    Assert.IsTrue
        (object.ReferenceEquals((object)(s0.Values[0]), (object)filemanFieldValue));
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanEntryTest))]
public void ItemGet382()
{
    FilemanFieldValue filemanFieldValue;
    FilemanEntry s0 = new FilemanEntry();
    s0.Ien = (string)null;
    s0.File = (FilemanFile)null;
    FilemanFieldValue[] filemanFieldValues = new FilemanFieldValue[2];
    s0.Values = filemanFieldValues;
    FilemanFieldValue s1 = new FilemanFieldValue();
    s1.Field = (FilemanField)null;
    s1.FieldNumber = "";
    s1.InternalValue = (string)null;
    s1.ExternalValue = (string)null;
    filemanFieldValues[0] = s1;
    FilemanFieldValue s2 = new FilemanFieldValue();
    s2.Field = (FilemanField)null;
    s2.FieldNumber = (string)null;
    s2.InternalValue = (string)null;
    s2.ExternalValue = (string)null;
    filemanFieldValues[1] = s2;
    filemanFieldValue = this.ItemGet(s0, (string)null);
    Assert.IsNotNull((object)filemanFieldValue);
    Assert.IsNull(filemanFieldValue.Field);
    Assert.AreEqual<string>((string)null, filemanFieldValue.FieldNumber);
    Assert.AreEqual<string>((string)null, filemanFieldValue.InternalValue);
    Assert.AreEqual<string>((string)null, filemanFieldValue.ExternalValue);
    Assert.IsNotNull((object)s0);
    Assert.AreEqual<string>((string)null, s0.Ien);
    Assert.IsNull(s0.File);
    Assert.IsNotNull(s0.Values);
    Assert.AreEqual<int>(2, s0.Values.Length);
    Assert.IsNotNull((object)(s0.Values[0]));
    Assert.IsNull(s0.Values[0].Field);
    Assert.AreEqual<string>("", s0.Values[0].FieldNumber);
    Assert.AreEqual<string>((string)null, s0.Values[0].InternalValue);
    Assert.AreEqual<string>((string)null, s0.Values[0].ExternalValue);
    Assert.IsNotNull((object)(s0.Values[1]));
    Assert.IsTrue
        (object.ReferenceEquals((object)(s0.Values[1]), (object)filemanFieldValue));
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanEntryTest))]
public void ItemGet96()
{
    FilemanFieldValue filemanFieldValue;
    FilemanEntry s0 = new FilemanEntry();
    s0.Ien = (string)null;
    s0.File = (FilemanFile)null;
    FilemanFieldValue[] filemanFieldValues = new FilemanFieldValue[2];
    s0.Values = filemanFieldValues;
    FilemanFieldValue s1 = new FilemanFieldValue();
    s1.Field = (FilemanField)null;
    s1.FieldNumber = "\0\0";
    s1.InternalValue = (string)null;
    s1.ExternalValue = (string)null;
    filemanFieldValues[0] = s1;
    filemanFieldValue = this.ItemGet(s0, (string)null);
    Assert.IsNull((object)filemanFieldValue);
    Assert.IsNotNull((object)s0);
    Assert.AreEqual<string>((string)null, s0.Ien);
    Assert.IsNull(s0.File);
    Assert.IsNotNull(s0.Values);
    Assert.AreEqual<int>(2, s0.Values.Length);
    Assert.IsNotNull((object)(s0.Values[0]));
    Assert.IsNull(s0.Values[0].Field);
    Assert.AreEqual<string>("\0\0", s0.Values[0].FieldNumber);
    Assert.AreEqual<string>((string)null, s0.Values[0].InternalValue);
    Assert.AreEqual<string>((string)null, s0.Values[0].ExternalValue);
    Assert.IsNull((object)(s0.Values[1]));
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanEntryTest))]
public void ItemGet375()
{
    FilemanFieldValue filemanFieldValue;
    FilemanEntry s0 = new FilemanEntry();
    s0.Ien = (string)null;
    s0.File = (FilemanFile)null;
    FilemanFieldValue[] filemanFieldValues = new FilemanFieldValue[4];
    s0.Values = filemanFieldValues;
    FilemanFieldValue s1 = new FilemanFieldValue();
    s1.Field = (FilemanField)null;
    s1.FieldNumber = "\0\0\0\0";
    s1.InternalValue = (string)null;
    s1.ExternalValue = (string)null;
    filemanFieldValues[0] = s1;
    FilemanFieldValue s2 = new FilemanFieldValue();
    s2.Field = (FilemanField)null;
    s2.FieldNumber = "\0\0\0\0";
    s2.InternalValue = (string)null;
    s2.ExternalValue = (string)null;
    filemanFieldValues[1] = s2;
    filemanFieldValue = this.ItemGet(s0, (string)null);
    Assert.IsNull((object)filemanFieldValue);
    Assert.IsNotNull((object)s0);
    Assert.AreEqual<string>((string)null, s0.Ien);
    Assert.IsNull(s0.File);
    Assert.IsNotNull(s0.Values);
    Assert.AreEqual<int>(4, s0.Values.Length);
    Assert.IsNotNull((object)(s0.Values[0]));
    Assert.IsNull(s0.Values[0].Field);
    Assert.AreEqual<string>("\0\0\0\0", s0.Values[0].FieldNumber);
    Assert.AreEqual<string>((string)null, s0.Values[0].InternalValue);
    Assert.AreEqual<string>((string)null, s0.Values[0].ExternalValue);
    Assert.IsNotNull((object)(s0.Values[1]));
    Assert.IsNull(s0.Values[1].Field);
    Assert.AreEqual<string>("\0\0\0\0", s0.Values[1].FieldNumber);
    Assert.AreEqual<string>((string)null, s0.Values[1].InternalValue);
    Assert.AreEqual<string>((string)null, s0.Values[1].ExternalValue);
    Assert.IsNull((object)(s0.Values[2]));
    Assert.IsNull((object)(s0.Values[3]));
}
    }
}
