// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace VistA.Imaging.DataNavigator.Model
{
    public partial class FilemanFileTest
    {
[TestMethod]
[PexGeneratedBy(typeof(FilemanFileTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ItemGetThrowsArgumentNullException881()
{
    FilemanField filemanField;
    FilemanFile s0 = new FilemanFile();
    s0.Name = (string)null;
    s0.Number = (string)null;
    s0.Fields = (FilemanField[])null;
    filemanField = this.ItemGet(s0, (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanFileTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ItemGetThrowsArgumentNullException313()
{
    FilemanField filemanField;
    FilemanFile s0 = new FilemanFile();
    s0.Name = (string)null;
    s0.Number = (string)null;
    s0.Fields = (FilemanField[])null;
    filemanField = this.ItemGet(s0, "");
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanFileTest))]
public void ItemGet740()
{
    FilemanField filemanField;
    FilemanFile s0 = new FilemanFile();
    s0.Name = (string)null;
    s0.Number = (string)null;
    s0.Fields = (FilemanField[])null;
    filemanField = this.ItemGet(s0, "\0");
    Assert.IsNull((object)filemanField);
    Assert.IsNotNull((object)s0);
    Assert.AreEqual<string>((string)null, s0.Name);
    Assert.AreEqual<string>((string)null, s0.Number);
    Assert.IsNull(s0.Fields);
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanFileTest))]
public void ItemGet422()
{
    FilemanField filemanField;
    FilemanFile s0 = new FilemanFile();
    s0.Name = (string)null;
    s0.Number = (string)null;
    FilemanField[] filemanFields = new FilemanField[0];
    s0.Fields = filemanFields;
    filemanField = this.ItemGet(s0, "\u0089");
    Assert.IsNull((object)filemanField);
    Assert.IsNotNull((object)s0);
    Assert.AreEqual<string>((string)null, s0.Name);
    Assert.AreEqual<string>((string)null, s0.Number);
    Assert.IsNotNull(s0.Fields);
    Assert.AreEqual<int>(0, s0.Fields.Length);
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanFileTest))]
public void ItemGet216()
{
    FilemanField filemanField;
    FilemanFile s0 = new FilemanFile();
    s0.Name = (string)null;
    s0.Number = (string)null;
    FilemanField[] filemanFields = new FilemanField[1];
    s0.Fields = filemanFields;
    filemanField = this.ItemGet(s0, "\u0089");
    Assert.IsNull((object)filemanField);
    Assert.IsNotNull((object)s0);
    Assert.AreEqual<string>((string)null, s0.Name);
    Assert.AreEqual<string>((string)null, s0.Number);
    Assert.IsNotNull(s0.Fields);
    Assert.AreEqual<int>(1, s0.Fields.Length);
    Assert.IsNull((object)(s0.Fields[0]));
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanFileTest))]
public void ItemGet455()
{
    FilemanField filemanField;
    FilemanFile s0 = new FilemanFile();
    s0.Name = (string)null;
    s0.Number = (string)null;
    FilemanField[] filemanFields = new FilemanField[1];
    s0.Fields = filemanFields;
    FilemanField s1 = new FilemanField();
    s1.DataType = (string)null;
    s1.File = (FilemanFile)null;
    s1.IsIndexed = false;
    s1.Name = (string)null;
    s1.Number = (string)null;
    s1.Pointer = (FilemanFilePointer)null;
    s1.PointerFileNumber = (string)null;
    filemanFields[0] = s1;
    filemanField = this.ItemGet(s0, "\u0089");
    Assert.IsNull((object)filemanField);
    Assert.IsNotNull((object)s0);
    Assert.AreEqual<string>((string)null, s0.Name);
    Assert.AreEqual<string>((string)null, s0.Number);
    Assert.IsNotNull(s0.Fields);
    Assert.AreEqual<int>(1, s0.Fields.Length);
    Assert.IsNotNull((object)(s0.Fields[0]));
    Assert.AreEqual<string>((string)null, s0.Fields[0].DataType);
    Assert.IsNull(s0.Fields[0].File);
    Assert.AreEqual<bool>(false, s0.Fields[0].IsIndexed);
    Assert.AreEqual<string>((string)null, s0.Fields[0].Name);
    Assert.AreEqual<string>((string)null, s0.Fields[0].Number);
    Assert.IsNull(s0.Fields[0].Pointer);
    Assert.AreEqual<string>((string)null, s0.Fields[0].PointerFileNumber);
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanFileTest))]
public void ItemGet135()
{
    FilemanField filemanField;
    FilemanFile s0 = new FilemanFile();
    s0.Name = (string)null;
    s0.Number = (string)null;
    FilemanField[] filemanFields = new FilemanField[1];
    s0.Fields = filemanFields;
    FilemanField s1 = new FilemanField();
    s1.DataType = (string)null;
    s1.File = (FilemanFile)null;
    s1.IsIndexed = false;
    s1.Name = (string)null;
    s1.Number = "\0";
    s1.Pointer = (FilemanFilePointer)null;
    s1.PointerFileNumber = (string)null;
    filemanFields[0] = s1;
    filemanField = this.ItemGet(s0, "\0");
    Assert.IsNotNull((object)filemanField);
    Assert.AreEqual<string>((string)null, filemanField.DataType);
    Assert.IsNull(filemanField.File);
    Assert.AreEqual<bool>(false, filemanField.IsIndexed);
    Assert.AreEqual<string>((string)null, filemanField.Name);
    Assert.AreEqual<string>("\0", filemanField.Number);
    Assert.IsNull(filemanField.Pointer);
    Assert.AreEqual<string>((string)null, filemanField.PointerFileNumber);
    Assert.IsNotNull((object)s0);
    Assert.AreEqual<string>((string)null, s0.Name);
    Assert.AreEqual<string>((string)null, s0.Number);
    Assert.IsNotNull(s0.Fields);
    Assert.AreEqual<int>(1, s0.Fields.Length);
    Assert.IsNotNull((object)(s0.Fields[0]));
    Assert.IsTrue
        (object.ReferenceEquals((object)(s0.Fields[0]), (object)filemanField));
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanFileTest))]
public void ItemGet964()
{
    FilemanField filemanField;
    FilemanFile s0 = new FilemanFile();
    s0.Name = (string)null;
    s0.Number = (string)null;
    FilemanField[] filemanFields = new FilemanField[2];
    s0.Fields = filemanFields;
    filemanField = this.ItemGet(s0, "\u0100");
    Assert.IsNull((object)filemanField);
    Assert.IsNotNull((object)s0);
    Assert.AreEqual<string>((string)null, s0.Name);
    Assert.AreEqual<string>((string)null, s0.Number);
    Assert.IsNotNull(s0.Fields);
    Assert.AreEqual<int>(2, s0.Fields.Length);
    Assert.IsNull((object)(s0.Fields[0]));
    Assert.IsNull((object)(s0.Fields[1]));
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanFileTest))]
public void ItemGet839()
{
    FilemanField filemanField;
    FilemanFile s0 = new FilemanFile();
    s0.Name = (string)null;
    s0.Number = (string)null;
    FilemanField[] filemanFields = new FilemanField[2];
    s0.Fields = filemanFields;
    FilemanField s1 = new FilemanField();
    s1.DataType = (string)null;
    s1.File = (FilemanFile)null;
    s1.IsIndexed = false;
    s1.Name = (string)null;
    s1.Number = (string)null;
    s1.Pointer = (FilemanFilePointer)null;
    s1.PointerFileNumber = (string)null;
    filemanFields[0] = s1;
    FilemanField s2 = new FilemanField();
    s2.DataType = (string)null;
    s2.File = (FilemanFile)null;
    s2.IsIndexed = false;
    s2.Name = (string)null;
    s2.Number = (string)null;
    s2.Pointer = (FilemanFilePointer)null;
    s2.PointerFileNumber = (string)null;
    filemanFields[1] = s2;
    filemanField = this.ItemGet(s0, "\u0100");
    Assert.IsNull((object)filemanField);
    Assert.IsNotNull((object)s0);
    Assert.AreEqual<string>((string)null, s0.Name);
    Assert.AreEqual<string>((string)null, s0.Number);
    Assert.IsNotNull(s0.Fields);
    Assert.AreEqual<int>(2, s0.Fields.Length);
    Assert.IsNotNull((object)(s0.Fields[0]));
    Assert.AreEqual<string>((string)null, s0.Fields[0].DataType);
    Assert.IsNull(s0.Fields[0].File);
    Assert.AreEqual<bool>(false, s0.Fields[0].IsIndexed);
    Assert.AreEqual<string>((string)null, s0.Fields[0].Name);
    Assert.AreEqual<string>((string)null, s0.Fields[0].Number);
    Assert.IsNull(s0.Fields[0].Pointer);
    Assert.AreEqual<string>((string)null, s0.Fields[0].PointerFileNumber);
    Assert.IsNotNull((object)(s0.Fields[1]));
    Assert.AreEqual<string>((string)null, s0.Fields[1].DataType);
    Assert.IsNull(s0.Fields[1].File);
    Assert.AreEqual<bool>(false, s0.Fields[1].IsIndexed);
    Assert.AreEqual<string>((string)null, s0.Fields[1].Name);
    Assert.AreEqual<string>((string)null, s0.Fields[1].Number);
    Assert.IsNull(s0.Fields[1].Pointer);
    Assert.AreEqual<string>((string)null, s0.Fields[1].PointerFileNumber);
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanFileTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ItemGetThrowsArgumentNullException479()
{
    FilemanField filemanField;
    FilemanFile s0 = new FilemanFile();
    s0.Name = (string)null;
    s0.Number = (string)null;
    s0.Fields = (FilemanField[])null;
    filemanField = this.ItemGet(s0, "\t\t");
}
    }
}
