// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using VistA.Imaging.DataNavigator.Repositories;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using VistA.Imaging.DataNavigator.Repositories.Moles;

namespace VistA.Imaging.DataNavigator.Model
{
    public partial class FilemanFieldPointerTest
    {
[TestMethod]
[PexGeneratedBy(typeof(FilemanFieldPointerTest))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException502()
{
    FilemanFieldPointer filemanFieldPointer;
    filemanFieldPointer =
      this.Constructor((IFilemanFileRepository)null, (FilemanField)null, 
                       (string)null, (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanFieldPointerTest))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException811()
{
    FilemanFieldPointer filemanFieldPointer;
    filemanFieldPointer = this.Constructor
                              ((IFilemanFileRepository)null, (FilemanField)null, (string)null, "");
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanFieldPointerTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException549()
{
    FilemanFieldPointer filemanFieldPointer;
    filemanFieldPointer = this.Constructor
                              ((IFilemanFileRepository)null, (FilemanField)null, (string)null, "\0");
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanFieldPointerTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException644()
{
    FilemanFieldPointer filemanFieldPointer;
    filemanFieldPointer = this.Constructor
                              ((IFilemanFileRepository)null, (FilemanField)null, (string)null, "\u0100");
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanFieldPointerTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException104()
{
    SIFilemanFileRepository sIFilemanFileRepository;
    FilemanFieldPointer filemanFieldPointer;
    sIFilemanFileRepository = new SIFilemanFileRepository();
    filemanFieldPointer = this.Constructor
                              ((IFilemanFileRepository)sIFilemanFileRepository, (FilemanField)null, 
                               (string)null, "\u0100");
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanFieldPointerTest))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException541()
{
    SIFilemanFileRepository sIFilemanFileRepository;
    FilemanFieldPointer filemanFieldPointer;
    sIFilemanFileRepository = new SIFilemanFileRepository();
    FilemanField s0 = new FilemanField();
    s0.DataType = (string)null;
    s0.File = (FilemanFile)null;
    s0.IsIndexed = false;
    s0.Name = (string)null;
    s0.Number = (string)null;
    s0.Pointer = (FilemanFilePointer)null;
    s0.PointerFileNumber = (string)null;
    filemanFieldPointer =
      this.Constructor((IFilemanFileRepository)sIFilemanFileRepository, s0, 
                       (string)null, "\u0100");
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanFieldPointerTest))]
public void Constructor769()
{
    SIFilemanFileRepository sIFilemanFileRepository;
    FilemanFieldPointer filemanFieldPointer;
    sIFilemanFileRepository = new SIFilemanFileRepository();
    FilemanField s0 = new FilemanField();
    s0.DataType = (string)null;
    s0.File = (FilemanFile)null;
    s0.IsIndexed = false;
    s0.Name = (string)null;
    s0.Number = (string)null;
    s0.Pointer = (FilemanFilePointer)null;
    s0.PointerFileNumber = (string)null;
    filemanFieldPointer = this.Constructor
                              ((IFilemanFileRepository)sIFilemanFileRepository, s0, "\u0100", "\u0100");
    Assert.IsNotNull((object)filemanFieldPointer);
    Assert.IsNotNull(((FilemanFilePointer)filemanFieldPointer).SourceField);
    Assert.AreEqual<string>((string)null, 
                            ((FilemanFilePointer)filemanFieldPointer).SourceField.DataType);
    Assert.IsNull(((FilemanFilePointer)filemanFieldPointer).SourceField.File);
    Assert.AreEqual<bool>
        (false, ((FilemanFilePointer)filemanFieldPointer).SourceField.IsIndexed);
    Assert.AreEqual<string>
        ((string)null, ((FilemanFilePointer)filemanFieldPointer).SourceField.Name);
    Assert.AreEqual<string>
        ((string)null, ((FilemanFilePointer)filemanFieldPointer).SourceField.Number);
    Assert.IsNull(((FilemanFilePointer)filemanFieldPointer).SourceField.Pointer);
    Assert.AreEqual<string>((string)null, 
                            ((FilemanFilePointer)filemanFieldPointer).SourceField.PointerFileNumber);
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanFieldPointerTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException763()
{
    FilemanFieldPointer filemanFieldPointer;
    filemanFieldPointer = this.Constructor
                              ((IFilemanFileRepository)null, (FilemanField)null, (string)null, "\0\0");
}
    }
}
