// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using VistA.Imaging.DataNavigator.Repositories;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Framework.Moles;
using VistA.Imaging.DataNavigator.Repositories.Moles;
using Microsoft.Pex.Framework;

namespace VistA.Imaging.DataNavigator.Model
{
    public partial class FilemanFieldPointerTest
    {
[TestMethod]
[PexGeneratedBy(typeof(FilemanFieldPointerTest))]
public void TargetFieldGet19103()
{
    using (PexChooseBehavedBehavior.Setup())
    {
      SIFilemanFileRepository sIFilemanFileRepository;
      FilemanFieldPointer filemanFieldPointer;
      FilemanField filemanField;
      sIFilemanFileRepository = new SIFilemanFileRepository();
      FilemanField s0 = new FilemanField();
      s0.DataType = (string)null;
      s0.File = (FilemanFile)null;
      s0.IsIndexed = false;
      s0.Name = (string)null;
      s0.Number = (string)null;
      s0.Pointer = (FilemanFilePointer)null;
      s0.PointerFileNumber = (string)null;
      filemanFieldPointer = new FilemanFieldPointer
                                ((IFilemanFileRepository)sIFilemanFileRepository, s0, "\u0100", "\u0100");
      IPexChoiceRecorder choices = PexChoose.Replay.Setup();
      FilemanFile s1 = new FilemanFile();
      s1.Name = (string)null;
      s1.Number = (string)null;
      FilemanField[] filemanFields = new FilemanField[0];
      s1.Fields = filemanFields;
      choices.NextSegment(2).DefaultSession
          .At(0, 
                                            "sIFilemanFileRepository.VistA.Imaging.DataNavigator.Repositories.ICachingRepository`2<VistA.Imaging.DataNavigator.Model.FilemanFile,System.String>.GetById", 
                                            (object)s1);
      filemanField = this.TargetFieldGet(filemanFieldPointer);
      Assert.IsNull((object)filemanField);
      Assert.IsNotNull((object)filemanFieldPointer);
      Assert.IsNotNull(((FilemanFilePointer)filemanFieldPointer).SourceField);
      Assert.AreEqual<string>((string)null, 
                              ((FilemanFilePointer)filemanFieldPointer).SourceField.DataType);
      Assert.IsNull(((FilemanFilePointer)filemanFieldPointer).SourceField.File);
      Assert.AreEqual<bool>
          (false, ((FilemanFilePointer)filemanFieldPointer).SourceField.IsIndexed);
      Assert.AreEqual<string>
          ((string)null, ((FilemanFilePointer)filemanFieldPointer).SourceField.Name);
      Assert.AreEqual<string>((string)null, 
                              ((FilemanFilePointer)filemanFieldPointer).SourceField.Number);
      Assert.IsNull(((FilemanFilePointer)filemanFieldPointer).SourceField.Pointer);
      Assert.AreEqual<string>((string)null, 
                              ((FilemanFilePointer)filemanFieldPointer).SourceField.PointerFileNumber);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanFieldPointerTest))]
public void TargetFieldGet19101()
{
    using (PexChooseBehavedBehavior.Setup())
    {
      SIFilemanFileRepository sIFilemanFileRepository;
      FilemanFieldPointer filemanFieldPointer;
      FilemanField filemanField;
      sIFilemanFileRepository = new SIFilemanFileRepository();
      FilemanField s0 = new FilemanField();
      s0.DataType = (string)null;
      s0.File = (FilemanFile)null;
      s0.IsIndexed = false;
      s0.Name = (string)null;
      s0.Number = (string)null;
      s0.Pointer = (FilemanFilePointer)null;
      s0.PointerFileNumber = (string)null;
      filemanFieldPointer = new FilemanFieldPointer
                                ((IFilemanFileRepository)sIFilemanFileRepository, s0, "\u0100", "\u0100");
      IPexChoiceRecorder choices = PexChoose.Replay.Setup();
      FilemanFile s1 = new FilemanFile();
      s1.Name = (string)null;
      s1.Number = (string)null;
      FilemanField[] filemanFields = new FilemanField[1];
      s1.Fields = filemanFields;
      choices.NextSegment(2).DefaultSession
          .At(0, 
                                            "sIFilemanFileRepository.VistA.Imaging.DataNavigator.Repositories.ICachingRepository`2<VistA.Imaging.DataNavigator.Model.FilemanFile,System.String>.GetById", 
                                            (object)s1);
      filemanField = this.TargetFieldGet(filemanFieldPointer);
      Assert.IsNull((object)filemanField);
      Assert.IsNotNull((object)filemanFieldPointer);
      Assert.IsNotNull(((FilemanFilePointer)filemanFieldPointer).SourceField);
      Assert.AreEqual<string>((string)null, 
                              ((FilemanFilePointer)filemanFieldPointer).SourceField.DataType);
      Assert.IsNull(((FilemanFilePointer)filemanFieldPointer).SourceField.File);
      Assert.AreEqual<bool>
          (false, ((FilemanFilePointer)filemanFieldPointer).SourceField.IsIndexed);
      Assert.AreEqual<string>
          ((string)null, ((FilemanFilePointer)filemanFieldPointer).SourceField.Name);
      Assert.AreEqual<string>((string)null, 
                              ((FilemanFilePointer)filemanFieldPointer).SourceField.Number);
      Assert.IsNull(((FilemanFilePointer)filemanFieldPointer).SourceField.Pointer);
      Assert.AreEqual<string>((string)null, 
                              ((FilemanFilePointer)filemanFieldPointer).SourceField.PointerFileNumber);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanFieldPointerTest))]
public void TargetFieldGet19102()
{
    using (PexChooseBehavedBehavior.Setup())
    {
      SIFilemanFileRepository sIFilemanFileRepository;
      FilemanFieldPointer filemanFieldPointer;
      FilemanField filemanField;
      sIFilemanFileRepository = new SIFilemanFileRepository();
      FilemanField s0 = new FilemanField();
      s0.DataType = (string)null;
      s0.File = (FilemanFile)null;
      s0.IsIndexed = false;
      s0.Name = (string)null;
      s0.Number = (string)null;
      s0.Pointer = (FilemanFilePointer)null;
      s0.PointerFileNumber = (string)null;
      filemanFieldPointer = new FilemanFieldPointer
                                ((IFilemanFileRepository)sIFilemanFileRepository, s0, "\u0100", "\u0100");
      IPexChoiceRecorder choices = PexChoose.Replay.Setup();
      FilemanFile s1 = new FilemanFile();
      s1.Name = (string)null;
      s1.Number = (string)null;
      FilemanField[] filemanFields = new FilemanField[1];
      s1.Fields = filemanFields;
      choices.NextSegment(2).DefaultSession
          .At(0, 
                                            "sIFilemanFileRepository.VistA.Imaging.DataNavigator.Repositories.ICachingRepository`2<VistA.Imaging.DataNavigator.Model.FilemanFile,System.String>.GetById", 
                                            (object)s1);
      FilemanField s2 = new FilemanField();
      s2.DataType = (string)null;
      s2.File = (FilemanFile)null;
      s2.IsIndexed = false;
      s2.Name = (string)null;
      s2.Number = (string)null;
      s2.Pointer = (FilemanFilePointer)null;
      s2.PointerFileNumber = (string)null;
      filemanFields[0] = s2;
      filemanField = this.TargetFieldGet(filemanFieldPointer);
      Assert.IsNull((object)filemanField);
      Assert.IsNotNull((object)filemanFieldPointer);
      Assert.IsNotNull(((FilemanFilePointer)filemanFieldPointer).SourceField);
      Assert.AreEqual<string>((string)null, 
                              ((FilemanFilePointer)filemanFieldPointer).SourceField.DataType);
      Assert.IsNull(((FilemanFilePointer)filemanFieldPointer).SourceField.File);
      Assert.AreEqual<bool>
          (false, ((FilemanFilePointer)filemanFieldPointer).SourceField.IsIndexed);
      Assert.AreEqual<string>
          ((string)null, ((FilemanFilePointer)filemanFieldPointer).SourceField.Name);
      Assert.AreEqual<string>((string)null, 
                              ((FilemanFilePointer)filemanFieldPointer).SourceField.Number);
      Assert.IsNull(((FilemanFilePointer)filemanFieldPointer).SourceField.Pointer);
      Assert.AreEqual<string>((string)null, 
                              ((FilemanFilePointer)filemanFieldPointer).SourceField.PointerFileNumber);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanFieldPointerTest))]
public void TargetFieldGet191()
{
    using (PexChooseBehavedBehavior.Setup())
    {
      SIFilemanFileRepository sIFilemanFileRepository;
      FilemanFieldPointer filemanFieldPointer;
      FilemanField filemanField;
      sIFilemanFileRepository = new SIFilemanFileRepository();
      FilemanField s0 = new FilemanField();
      s0.DataType = (string)null;
      s0.File = (FilemanFile)null;
      s0.IsIndexed = false;
      s0.Name = (string)null;
      s0.Number = (string)null;
      s0.Pointer = (FilemanFilePointer)null;
      s0.PointerFileNumber = (string)null;
      filemanFieldPointer = new FilemanFieldPointer
                                ((IFilemanFileRepository)sIFilemanFileRepository, s0, "\u0100", "\u0100");
      filemanField = this.TargetFieldGet(filemanFieldPointer);
      Assert.IsNull((object)filemanField);
      Assert.IsNotNull((object)filemanFieldPointer);
      Assert.IsNotNull(((FilemanFilePointer)filemanFieldPointer).SourceField);
      Assert.AreEqual<string>((string)null, 
                              ((FilemanFilePointer)filemanFieldPointer).SourceField.DataType);
      Assert.IsNull(((FilemanFilePointer)filemanFieldPointer).SourceField.File);
      Assert.AreEqual<bool>
          (false, ((FilemanFilePointer)filemanFieldPointer).SourceField.IsIndexed);
      Assert.AreEqual<string>
          ((string)null, ((FilemanFilePointer)filemanFieldPointer).SourceField.Name);
      Assert.AreEqual<string>((string)null, 
                              ((FilemanFilePointer)filemanFieldPointer).SourceField.Number);
      Assert.IsNull(((FilemanFilePointer)filemanFieldPointer).SourceField.Pointer);
      Assert.AreEqual<string>((string)null, 
                              ((FilemanFilePointer)filemanFieldPointer).SourceField.PointerFileNumber);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanFieldPointerTest))]
public void TargetFieldGet19110()
{
    using (PexChooseBehavedBehavior.Setup())
    {
      SIFilemanFileRepository sIFilemanFileRepository;
      FilemanFieldPointer filemanFieldPointer;
      FilemanField filemanField;
      sIFilemanFileRepository = new SIFilemanFileRepository();
      FilemanField s0 = new FilemanField();
      s0.DataType = (string)null;
      s0.File = (FilemanFile)null;
      s0.IsIndexed = false;
      s0.Name = (string)null;
      s0.Number = (string)null;
      s0.Pointer = (FilemanFilePointer)null;
      s0.PointerFileNumber = (string)null;
      filemanFieldPointer = new FilemanFieldPointer
                                ((IFilemanFileRepository)sIFilemanFileRepository, s0, "\u0100", "\u0100");
      IPexChoiceRecorder choices = PexChoose.Replay.Setup();
      FilemanFile s1 = new FilemanFile();
      s1.Name = (string)null;
      s1.Number = (string)null;
      FilemanField[] filemanFields = new FilemanField[2];
      s1.Fields = filemanFields;
      choices.NextSegment(2).DefaultSession
          .At(0, 
                                            "sIFilemanFileRepository.VistA.Imaging.DataNavigator.Repositories.ICachingRepository`2<VistA.Imaging.DataNavigator.Model.FilemanFile,System.String>.GetById", 
                                            (object)s1);
      filemanField = this.TargetFieldGet(filemanFieldPointer);
      Assert.IsNull((object)filemanField);
      Assert.IsNotNull((object)filemanFieldPointer);
      Assert.IsNotNull(((FilemanFilePointer)filemanFieldPointer).SourceField);
      Assert.AreEqual<string>((string)null, 
                              ((FilemanFilePointer)filemanFieldPointer).SourceField.DataType);
      Assert.IsNull(((FilemanFilePointer)filemanFieldPointer).SourceField.File);
      Assert.AreEqual<bool>
          (false, ((FilemanFilePointer)filemanFieldPointer).SourceField.IsIndexed);
      Assert.AreEqual<string>
          ((string)null, ((FilemanFilePointer)filemanFieldPointer).SourceField.Name);
      Assert.AreEqual<string>((string)null, 
                              ((FilemanFilePointer)filemanFieldPointer).SourceField.Number);
      Assert.IsNull(((FilemanFilePointer)filemanFieldPointer).SourceField.Pointer);
      Assert.AreEqual<string>((string)null, 
                              ((FilemanFilePointer)filemanFieldPointer).SourceField.PointerFileNumber);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanFieldPointerTest))]
public void TargetFieldGet19111()
{
    using (PexChooseBehavedBehavior.Setup())
    {
      SIFilemanFileRepository sIFilemanFileRepository;
      FilemanFieldPointer filemanFieldPointer;
      FilemanField filemanField;
      sIFilemanFileRepository = new SIFilemanFileRepository();
      FilemanField s0 = new FilemanField();
      s0.DataType = (string)null;
      s0.File = (FilemanFile)null;
      s0.IsIndexed = false;
      s0.Name = (string)null;
      s0.Number = (string)null;
      s0.Pointer = (FilemanFilePointer)null;
      s0.PointerFileNumber = (string)null;
      filemanFieldPointer = new FilemanFieldPointer
                                ((IFilemanFileRepository)sIFilemanFileRepository, s0, "\u0100", "\u0100");
      IPexChoiceRecorder choices = PexChoose.Replay.Setup();
      FilemanFile s1 = new FilemanFile();
      s1.Name = (string)null;
      s1.Number = (string)null;
      FilemanField[] filemanFields = new FilemanField[3];
      s1.Fields = filemanFields;
      choices.NextSegment(2).DefaultSession
          .At(0, 
                                            "sIFilemanFileRepository.VistA.Imaging.DataNavigator.Repositories.ICachingRepository`2<VistA.Imaging.DataNavigator.Model.FilemanFile,System.String>.GetById", 
                                            (object)s1);
      FilemanField s2 = new FilemanField();
      s2.DataType = (string)null;
      s2.File = (FilemanFile)null;
      s2.IsIndexed = false;
      s2.Name = (string)null;
      s2.Number = (string)null;
      s2.Pointer = (FilemanFilePointer)null;
      s2.PointerFileNumber = (string)null;
      filemanFields[1] = s2;
      FilemanField s3 = new FilemanField();
      s3.DataType = (string)null;
      s3.File = (FilemanFile)null;
      s3.IsIndexed = false;
      s3.Name = (string)null;
      s3.Number = (string)null;
      s3.Pointer = (FilemanFilePointer)null;
      s3.PointerFileNumber = (string)null;
      filemanFields[2] = s3;
      filemanField = this.TargetFieldGet(filemanFieldPointer);
      Assert.IsNull((object)filemanField);
      Assert.IsNotNull((object)filemanFieldPointer);
      Assert.IsNotNull(((FilemanFilePointer)filemanFieldPointer).SourceField);
      Assert.AreEqual<string>((string)null, 
                              ((FilemanFilePointer)filemanFieldPointer).SourceField.DataType);
      Assert.IsNull(((FilemanFilePointer)filemanFieldPointer).SourceField.File);
      Assert.AreEqual<bool>
          (false, ((FilemanFilePointer)filemanFieldPointer).SourceField.IsIndexed);
      Assert.AreEqual<string>
          ((string)null, ((FilemanFilePointer)filemanFieldPointer).SourceField.Name);
      Assert.AreEqual<string>((string)null, 
                              ((FilemanFilePointer)filemanFieldPointer).SourceField.Number);
      Assert.IsNull(((FilemanFilePointer)filemanFieldPointer).SourceField.Pointer);
      Assert.AreEqual<string>((string)null, 
                              ((FilemanFilePointer)filemanFieldPointer).SourceField.PointerFileNumber);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanFieldPointerTest))]
public void TargetFieldGet19105()
{
    using (PexChooseBehavedBehavior.Setup())
    {
      SIFilemanFileRepository sIFilemanFileRepository;
      FilemanFieldPointer filemanFieldPointer;
      FilemanField filemanField;
      sIFilemanFileRepository = new SIFilemanFileRepository();
      FilemanField s0 = new FilemanField();
      s0.DataType = (string)null;
      s0.File = (FilemanFile)null;
      s0.IsIndexed = false;
      s0.Name = (string)null;
      s0.Number = (string)null;
      s0.Pointer = (FilemanFilePointer)null;
      s0.PointerFileNumber = (string)null;
      filemanFieldPointer = new FilemanFieldPointer
                                ((IFilemanFileRepository)sIFilemanFileRepository, s0, "\u0100", "\u0100");
      IPexChoiceRecorder choices = PexChoose.Replay.Setup();
      FilemanFile s1 = new FilemanFile();
      s1.Name = (string)null;
      s1.Number = (string)null;
      s1.Fields = (FilemanField[])null;
      choices.NextSegment(2).DefaultSession
          .At(0, 
                                            "sIFilemanFileRepository.VistA.Imaging.DataNavigator.Repositories.ICachingRepository`2<VistA.Imaging.DataNavigator.Model.FilemanFile,System.String>.GetById", 
                                            (object)s1);
      filemanField = this.TargetFieldGet(filemanFieldPointer);
      Assert.IsNull((object)filemanField);
      Assert.IsNotNull((object)filemanFieldPointer);
      Assert.IsNotNull(((FilemanFilePointer)filemanFieldPointer).SourceField);
      Assert.AreEqual<string>((string)null, 
                              ((FilemanFilePointer)filemanFieldPointer).SourceField.DataType);
      Assert.IsNull(((FilemanFilePointer)filemanFieldPointer).SourceField.File);
      Assert.AreEqual<bool>
          (false, ((FilemanFilePointer)filemanFieldPointer).SourceField.IsIndexed);
      Assert.AreEqual<string>
          ((string)null, ((FilemanFilePointer)filemanFieldPointer).SourceField.Name);
      Assert.AreEqual<string>((string)null, 
                              ((FilemanFilePointer)filemanFieldPointer).SourceField.Number);
      Assert.IsNull(((FilemanFilePointer)filemanFieldPointer).SourceField.Pointer);
      Assert.AreEqual<string>((string)null, 
                              ((FilemanFilePointer)filemanFieldPointer).SourceField.PointerFileNumber);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanFieldPointerTest))]
public void TargetFieldGet243()
{
    using (PexChooseBehavedBehavior.Setup())
    {
      SIFilemanFileRepository sIFilemanFileRepository;
      FilemanFieldPointer filemanFieldPointer;
      FilemanField filemanField;
      sIFilemanFileRepository = new SIFilemanFileRepository();
      FilemanField s0 = new FilemanField();
      s0.DataType = (string)null;
      s0.File = (FilemanFile)null;
      s0.IsIndexed = false;
      s0.Name = (string)null;
      s0.Number = (string)null;
      s0.Pointer = (FilemanFilePointer)null;
      s0.PointerFileNumber = (string)null;
      filemanFieldPointer = new FilemanFieldPointer
                                ((IFilemanFileRepository)sIFilemanFileRepository, s0, "\u0100", "\u0200");
      IPexChoiceRecorder choices = PexChoose.Replay.Setup();
      FilemanFile s1 = new FilemanFile();
      s1.Name = (string)null;
      s1.Number = (string)null;
      FilemanField[] filemanFields = new FilemanField[1];
      s1.Fields = filemanFields;
      choices.NextSegment(2).DefaultSession
          .At(0, 
                                            "sIFilemanFileRepository.VistA.Imaging.DataNavigator.Repositories.ICachingRepository`2<VistA.Imaging.DataNavigator.Model.FilemanFile,System.String>.GetById", 
                                            (object)s1);
      FilemanField s2 = new FilemanField();
      s2.DataType = (string)null;
      s2.File = (FilemanFile)null;
      s2.IsIndexed = false;
      s2.Name = (string)null;
      s2.Number = "\u0200";
      s2.Pointer = (FilemanFilePointer)null;
      s2.PointerFileNumber = (string)null;
      filemanFields[0] = s2;
      filemanField = this.TargetFieldGet(filemanFieldPointer);
      Assert.IsNotNull((object)filemanField);
      Assert.AreEqual<string>((string)null, filemanField.DataType);
      Assert.IsNull(filemanField.File);
      Assert.AreEqual<bool>(false, filemanField.IsIndexed);
      Assert.AreEqual<string>((string)null, filemanField.Name);
      Assert.AreEqual<string>("\u0200", filemanField.Number);
      Assert.IsNull(filemanField.Pointer);
      Assert.AreEqual<string>((string)null, filemanField.PointerFileNumber);
      Assert.IsNotNull((object)filemanFieldPointer);
      Assert.IsNotNull(((FilemanFilePointer)filemanFieldPointer).SourceField);
      Assert.AreEqual<string>((string)null, 
                              ((FilemanFilePointer)filemanFieldPointer).SourceField.DataType);
      Assert.IsNull(((FilemanFilePointer)filemanFieldPointer).SourceField.File);
      Assert.AreEqual<bool>
          (false, ((FilemanFilePointer)filemanFieldPointer).SourceField.IsIndexed);
      Assert.AreEqual<string>
          ((string)null, ((FilemanFilePointer)filemanFieldPointer).SourceField.Name);
      Assert.AreEqual<string>((string)null, 
                              ((FilemanFilePointer)filemanFieldPointer).SourceField.Number);
      Assert.IsNull(((FilemanFilePointer)filemanFieldPointer).SourceField.Pointer);
      Assert.AreEqual<string>((string)null, 
                              ((FilemanFilePointer)filemanFieldPointer).SourceField.PointerFileNumber);
    }
}
    }
}
