// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.ComponentModel;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace VistA.Imaging.DataNavigator.Model
{
    public partial class FilemanFieldValueComparerTest
    {
[TestMethod]
[PexGeneratedBy(typeof(FilemanFieldValueComparerTest))]
public void Compare0118()
{
    int i;
    FilemanFieldValueComparer s0
       = new FilemanFieldValueComparer(default(ListSortDirection?));
    i = this.Compare01(s0, (object)null, (object)null);
    Assert.AreEqual<int>(0, i);
    Assert.IsNotNull((object)s0);
    Assert.IsNull((object)(s0.Direction));
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanFieldValueComparerTest))]
public void Compare01959()
{
    int i;
    FilemanFieldValueComparer s0
       = new FilemanFieldValueComparer(default(ListSortDirection?));
    FilemanFieldValue s1 = new FilemanFieldValue();
    s1.Field = (FilemanField)null;
    s1.FieldNumber = (string)null;
    s1.InternalValue = (string)null;
    s1.ExternalValue = (string)null;
    i = this.Compare01(s0, (object)null, (object)s1);
    Assert.AreEqual<int>(-1, i);
    Assert.IsNotNull((object)s0);
    Assert.IsNull((object)(s0.Direction));
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanFieldValueComparerTest))]
public void Compare01666()
{
    int i;
    FilemanFieldValueComparer s0
       = new FilemanFieldValueComparer(default(ListSortDirection?));
    FilemanFieldValue s1 = new FilemanFieldValue();
    s1.Field = (FilemanField)null;
    s1.FieldNumber = (string)null;
    s1.InternalValue = (string)null;
    s1.ExternalValue = (string)null;
    i = this.Compare01(s0, (object)s1, (object)null);
    Assert.AreEqual<int>(1, i);
    Assert.IsNotNull((object)s0);
    Assert.IsNull((object)(s0.Direction));
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanFieldValueComparerTest))]
public void Compare01932()
{
    int i;
    FilemanFieldValueComparer s0
       = new FilemanFieldValueComparer(default(ListSortDirection?));
    FilemanFieldValue s1 = new FilemanFieldValue();
    s1.Field = (FilemanField)null;
    s1.FieldNumber = (string)null;
    s1.InternalValue = (string)null;
    s1.ExternalValue = (string)null;
    FilemanFieldValue s2 = new FilemanFieldValue();
    s2.Field = (FilemanField)null;
    s2.FieldNumber = (string)null;
    s2.InternalValue = (string)null;
    s2.ExternalValue = (string)null;
    i = this.Compare01(s0, (object)s1, (object)s2);
    Assert.AreEqual<int>(0, i);
    Assert.IsNotNull((object)s0);
    Assert.IsNull((object)(s0.Direction));
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanFieldValueComparerTest))]
public void Compare01637()
{
    int i;
    FilemanFieldValueComparer s0
       = new FilemanFieldValueComparer(default(ListSortDirection?));
    FilemanFieldValue s1 = new FilemanFieldValue();
    s1.Field = (FilemanField)null;
    s1.FieldNumber = "";
    s1.InternalValue = (string)null;
    s1.ExternalValue = (string)null;
    FilemanFieldValue s2 = new FilemanFieldValue();
    s2.Field = (FilemanField)null;
    s2.FieldNumber = (string)null;
    s2.InternalValue = (string)null;
    s2.ExternalValue = (string)null;
    i = this.Compare01(s0, (object)s1, (object)s2);
    Assert.AreEqual<int>(0, i);
    Assert.IsNotNull((object)s0);
    Assert.IsNull((object)(s0.Direction));
}
[TestMethod]
[PexGeneratedBy(typeof(FilemanFieldValueComparerTest))]
public void Compare01366()
{
    int i;
    FilemanFieldValueComparer s0 = new FilemanFieldValueComparer
                                       (new ListSortDirection?(ListSortDirection.Descending));
    object boxi = (object)(default(int));
    i = this.Compare01(s0, boxi, (object)null);
    Assert.AreEqual<int>(0, i);
    Assert.IsNotNull((object)s0);
    Assert.IsNotNull((object)(s0.Direction));
    Assert.AreEqual<ListSortDirection>
        (ListSortDirection.Descending, (ListSortDirection)((object)(s0.Direction)));
}
    }
}
