// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace VistA.Imaging.DataNavigator.Model
{
    public partial class FilemanFileTest
    {
[TestMethod]
[PexGeneratedBy(typeof(FilemanFileTest))]
public void ToString01332()
{
    string s;
    FilemanFile s0 = new FilemanFile();
    s0.Name = (string)null;
    s0.Number = (string)null;
    s0.Fields = (FilemanField[])null;
    s = this.ToString01(s0);
    Assert.AreEqual<string>(" ()", s);
    Assert.IsNotNull((object)s0);
    Assert.AreEqual<string>((string)null, s0.Name);
    Assert.AreEqual<string>((string)null, s0.Number);
    Assert.IsNull(s0.Fields);
}
    }
}
