// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace VistA.Imaging.DataNavigator.Model
{
    public partial class FilemanFieldTest
    {
[TestMethod]
[PexGeneratedBy(typeof(FilemanFieldTest))]
public void ToString01322()
{
    string s;
    FilemanField s0 = new FilemanField();
    s0.DataType = (string)null;
    s0.File = (FilemanFile)null;
    s0.IsIndexed = false;
    s0.Name = (string)null;
    s0.Number = (string)null;
    s0.Pointer = (FilemanFilePointer)null;
    s0.PointerFileNumber = (string)null;
    s = this.ToString01(s0);
    Assert.AreEqual<string>(" ()", s);
    Assert.IsNotNull((object)s0);
    Assert.AreEqual<string>((string)null, s0.DataType);
    Assert.IsNull(s0.File);
    Assert.AreEqual<bool>(false, s0.IsIndexed);
    Assert.AreEqual<string>((string)null, s0.Name);
    Assert.AreEqual<string>((string)null, s0.Number);
    Assert.IsNull(s0.Pointer);
    Assert.AreEqual<string>((string)null, s0.PointerFileNumber);
}
    }
}
