// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace VistA.Imaging.DataNavigator.Model
{
    public partial class SearchTypeTest
    {
[TestMethod]
[PexGeneratedBy(typeof(SearchTypeTest))]
public void ToString01944()
{
    string s;
    SearchType s0 = new SearchType();
    FilemanField s1 = new FilemanField();
    s1.DataType = (string)null;
    FilemanFile s2 = new FilemanFile();
    s2.Name = (string)null;
    s2.Number = (string)null;
    s2.Fields = (FilemanField[])null;
    s1.File = s2;
    s1.IsIndexed = false;
    s1.Name = (string)null;
    s1.Number = (string)null;
    s1.Pointer = (FilemanFilePointer)null;
    s1.PointerFileNumber = (string)null;
    s0.Field = s1;
    s = this.ToString01(s0);
    Assert.AreEqual<string>("() ()", s);
    Assert.IsNotNull((object)s0);
    Assert.IsNotNull(s0.Field);
    Assert.AreEqual<string>((string)null, s0.Field.DataType);
    Assert.IsNotNull(s0.Field.File);
    Assert.AreEqual<string>((string)null, s0.Field.File.Name);
    Assert.AreEqual<string>((string)null, s0.Field.File.Number);
    Assert.IsNull(s0.Field.File.Fields);
    Assert.AreEqual<bool>(false, s0.Field.IsIndexed);
    Assert.AreEqual<string>((string)null, s0.Field.Name);
    Assert.AreEqual<string>((string)null, s0.Field.Number);
    Assert.IsNull(s0.Field.Pointer);
    Assert.AreEqual<string>((string)null, s0.Field.PointerFileNumber);
}
[TestMethod]
[PexGeneratedBy(typeof(SearchTypeTest))]
public void ToString01256()
{
    string s;
    SearchType s0 = new SearchType();
    s0.Field = (FilemanField)null;
    s = this.ToString01(s0);
    Assert.AreEqual<string>("VistA.Imaging.DataNavigator.Model.SearchType", s);
    Assert.IsNotNull((object)s0);
    Assert.IsNull(s0.Field);
}
[TestMethod]
[PexGeneratedBy(typeof(SearchTypeTest))]
public void ToString01935()
{
    string s;
    SearchType s0 = new SearchType();
    FilemanField s1 = new FilemanField();
    s1.DataType = (string)null;
    s1.File = (FilemanFile)null;
    s1.IsIndexed = false;
    s1.Name = (string)null;
    s1.Number = (string)null;
    s1.Pointer = (FilemanFilePointer)null;
    s1.PointerFileNumber = (string)null;
    s0.Field = s1;
    s = this.ToString01(s0);
    Assert.AreEqual<string>("VistA.Imaging.DataNavigator.Model.SearchType", s);
    Assert.IsNotNull((object)s0);
    Assert.IsNotNull(s0.Field);
    Assert.AreEqual<string>((string)null, s0.Field.DataType);
    Assert.IsNull(s0.Field.File);
    Assert.AreEqual<bool>(false, s0.Field.IsIndexed);
    Assert.AreEqual<string>((string)null, s0.Field.Name);
    Assert.AreEqual<string>((string)null, s0.Field.Number);
    Assert.IsNull(s0.Field.Pointer);
    Assert.AreEqual<string>((string)null, s0.Field.PointerFileNumber);
}
    }
}
