/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class gov_va_med_imaging_storage_IconImageCreation */

#ifndef _Included_gov_va_med_imaging_storage_IconImageCreation
#define _Included_gov_va_med_imaging_storage_IconImageCreation
#ifdef __cplusplus
extern "C" {
#endif

//typedef int jint;
/*
 * Class:     gov_va_med_imaging_storage_IconImageCreation
 * Method:    createIconImage
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gov_va_med_imaging_storage_IconImageCreation_createIconImage	(JNIEnv *, jclass, jstring, jstring);
#ifdef __cplusplus
}
#endif
#endif
